// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLio5JD9ncoHnUtw4Hb3ER5_6NSEEFJX0',
    appId: '1:90594371654:web:11ca00e262733e40240247',
    messagingSenderId: '90594371654',
    projectId: 'veto-52c25',
    authDomain: 'veto-52c25.firebaseapp.com',
    storageBucket: 'veto-52c25.appspot.com',
    measurementId: 'G-Z728N88HQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJXK0kMYTGPAP9RRnnANzN-_GHYJXwu6A',
    appId: '1:90594371654:android:83b0bb75e65cf705240247',
    messagingSenderId: '90594371654',
    projectId: 'veto-52c25',
    storageBucket: 'veto-52c25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiBJM7iamh53ejGxyo3Xor1VAplJWD1ZE',
    appId: '1:90594371654:ios:27c3b9182b60ab90240247',
    messagingSenderId: '90594371654',
    projectId: 'veto-52c25',
    storageBucket: 'veto-52c25.appspot.com',
    iosBundleId: 'com.example.vetoRenewApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiBJM7iamh53ejGxyo3Xor1VAplJWD1ZE',
    appId: '1:90594371654:ios:27c3b9182b60ab90240247',
    messagingSenderId: '90594371654',
    projectId: 'veto-52c25',
    storageBucket: 'veto-52c25.appspot.com',
    iosBundleId: 'com.example.vetoRenewApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLio5JD9ncoHnUtw4Hb3ER5_6NSEEFJX0',
    appId: '1:90594371654:web:b853d2da8ac40b82240247',
    messagingSenderId: '90594371654',
    projectId: 'veto-52c25',
    authDomain: 'veto-52c25.firebaseapp.com',
    storageBucket: 'veto-52c25.appspot.com',
    measurementId: 'G-NFG87JZR55',
  );

}